#!/bin/bash
function installgit() {
	mv ~/.ssh/authorized_keys ~/authorized_keys.custom 2>/dev/null
	touch ~/authorized_keys.custom
	mkdir -p ~/.ssh || exit 1
	mkdir -p ~/var ~/var/tmp ~/var/locks ~/var/cache ~/repos || exit 1
	cp -a gitjoin/ webapp/ *.py ~ || exit 1
	bash genconf.sh > ~/config.py
	echo Ok. Now edit $HOME/config.py
}

if [ "$(whoami)" = root ]; then
	printf "Enter name of user to create (empty to abort): "
	read username
	if [ "$username" = "" ]; then
		echo Abort.
		exit 1
	fi
	useradd $username
	home=`su $username -c 'echo ~'`
	if [ "$home" = "" ]; then
		echo Failed to get home directory of $username.
		exit 1
	fi
	mkdir -p $home || exit
	chown $username $home || exit
	su $username -c "bash $0"
else
	printf "Overwrite %s? (uppercase yes/no): " "$HOME"
	read yesorno

	if [ "$yesorno" = YES ]; then
		echo "Installing..."
		installgit
	else
		echo Cancel.
		exit 1
	fi
fi
