#!/bin/bash
# Gitjoin Git Management
# Copyright (C) 2012 Michal Zielinski
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
set -e

cd $(dirname $0)
. activate.inc

mkdir -p var/tmp var/locks var/cache repos

echo Syncing DB...
./manage.py syncdb --noinput
./manage.py evolve --noinput --hint -x

echo Collecting static files...
./manage.py collectstatic --noinput >/dev/null
#echo Clearing cache...
#rm -r ~/var/cache/*

echo Regenerating authorized keys...
python -m gitjoin.authorized_keys

echo Regenerating hooks...
python -m gitjoin.hooks regen

echo Updated.
