#!/bin/bash
cd $(dirname $0)

if [ `whoami` = root ]; then
	echo Run ./update as Git user. >&2
	exit 1
fi

if [ ! -e ~/GITJOIN_AUTOINSTALLED ]; then
	echo ~/GITJOIN_AUTOINSTALLED does not exist - installation was not performed by ./setup >&2
	echo Make sure that you run ./update as Git user >&2
	exit 1
fi

if [ "$1" != no-pull -a -w .git ]; then
    echo Pulling changes
	git pull
	if [ $? != 0 ]; then
	    echo Pull failed. Run "./update no-pull" to skip git pull
	    exit 1
	fi
	echo Chaining to new update script
	exec ./update no-pull
else
	if [ "$1" != no-pull ]; then
	    echo Not doing 'git pull' - not git repository or .git not writeable
	fi
fi

cp -a gitjoin/ webapp/ *.py ~ || exit 1
echo Syncing DB...
~/manage.py syncdb --noinput
~/manage.py evolve --noinput --hint -x
echo Collecting static files...
~/manage.py collectstatic --noinput >/dev/null
#echo Clearing cache...
#rm -r ~/var/cache/*
setfacl -R -m u:apache:rx ~/var/static
touch ~/wsgi.py
echo Updated.